spring:
  datasource:
    url: jdbc:mysql://124.71.224.210:3306/cmp?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: tarena2017Up;
logging:
  level:
    com.tarena.passport: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml