spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cmp?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
logging:
  level:
    com.tarena.passport: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml